question_data = [
    {"text": "At terminal velocity, all motion stops.", "answer": "false"},
    {"text": "Your mass on Earth is different than your mass on Mars.", "answer": "false"},
    {"text": "A rocket is propelled through space by the exhaust gases pushing against air.", "answer": "false"},
    {"text": "In a vacuum, all objects fall toward the center of the Earth with the same acceleration.", "answer": "true"},
    {"text": "Three skydivers tied together fall faster than a single skydiver.", "answer": "false"},
    {"text": "Linear momentum is always conserved.", "answer": "true"},
    {"text": "Angular momentum is always conserved.", "answer": "true"},
    {"text": "Centrifugal force exists only in rotating objects", "answer": "false"},
    {"text": "You can predict how many electrons an element will gain or lose by looking at its valence electrons.",
     "answer": "true"},
    {"text": "Elements of group eight are very reactive", "answer": "false"},
    {"text": "Using 4 kWh of power is equivalent to using 2000 W of power for 2 h", "answer": "true"},
    {"text": "The current through a resistor can be found by dividing the resistor's voltage by its ohmic value.",
        "answer": "true"},
    {"text": "The voltage drop across a resistor is simply a difference of potential across that resistor.",
     "answer": "true"},
    {"text": "Doubling the voltage across a resistor will cut the current by half.", "answer": "false"},
    {"text": "Padding decreases the effect of a collision by increasing the contact time.", "answer": "false"},
    {"text": "Molecules are formed by covalent bonds which are weaker bonds than ionic bonds.", "answer": "true"},
    {"text": "Ionization is the process of adding iodine to salt, making iodized salt", "answer": "false"},
    {"text": "Electronegativity is the atom's ability to attract more electrons", "answer": "true"},
    {"text": "Group seven will most likely lose one electron", "answer": "false"}
]
